name: Update Dependabot Lockfile
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'pnpm-workspace.yaml'

jobs:
  update-lockfile:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: package.json
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - uses: suzuki-shunsuke/commit-action@f28421acc277a6d6a9c1f94ea449076ad77dba67 # v0.1.0
        with:
          app_id: ${{ vars.CURIO_MACHINE_APP_ID }}
          app_private_key: ${{ secrets.CURIO_MACHINE_PRIVATE_KEY }}
          fail_on_self_push: false
          commit_message: '[Auto-generated] update lockfile'
