name: VRT Approve
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'VRT approve target'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - extension
          - mobile

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.CURIO_MACHINE_APP_ID }}
          private-key: ${{ secrets.CURIO_MACHINE_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.ref_name }}
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: package.json
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Japanese and emoji fonts
        run: sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji
      - name: Build
        if: inputs.target == 'all' || inputs.target == 'extension'
        run: pnpm build
      - name: VRT Approve (Extension)
        if: inputs.target == 'all' || inputs.target == 'extension'
        run: pnpm --filter @curio/extension vrt:approve
      - name: VRT Approve (Mobile)
        if: inputs.target == 'all' || inputs.target == 'mobile'
        run: pnpm --filter @curio/mobile vrt:approve
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Commit VRT Approvals
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git add .
          git commit -m "[Auto-generated] vrt approve" --no-verify
          git push origin ${{ github.ref_name }} --no-verify
